/* ===========================================================
   FreshBite - Static Data
   Arrays used to dynamically render pages across the site.
   =========================================================== */

// ---------- Food Categories ----------
const categories = [
  { id: 1, name: "Pizza", icon: "fa-solid fa-pizza-slice", itemCount: 24 },
  { id: 2, name: "Burgers", icon: "fa-solid fa-burger", itemCount: 18 },
  { id: 3, name: "Somali Food", icon: "fa-solid fa-drumstick-bite", itemCount: 15 },
  { id: 4, name: "Chicken", icon: "fa-solid fa-kiwi-bird", itemCount: 20 },
  { id: 5, name: "Desserts", icon: "fa-solid fa-ice-cream", itemCount: 12 },
  { id: 6, name: "Drinks", icon: "fa-solid fa-mug-saucer", itemCount: 16 },
];

// ---------- Featured Restaurants ----------
// priceLevel: 1 = $, 2 = $$, 3 = $$$
// deliveryTimeMin: numeric minutes used for sorting/filtering
const restaurants = [
  {
    id: 1,
    name: "Bella Italia",
    cuisine: "Italian, Pizza",
    description: "Authentic wood-fired pizzas and handmade pasta using traditional Italian recipes.",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?auto=format&fit=crop&w=200&q=80",
    rating: 4.8,
    reviewCount: 1245,
    deliveryTime: "20-30 min",
    deliveryTimeMin: 25,
    deliveryFee: 2.5,
    priceLevel: 2,
    isOpen: true,
    minOrder: 10,
    dietaryOptions: ["Vegetarian"],
  },
  {
    id: 2,
    name: "Burger Junction",
    cuisine: "American, Burgers",
    description: "Juicy flame-grilled burgers stacked high with fresh toppings and house-made sauces.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=200&q=80",
    rating: 4.6,
    reviewCount: 980,
    deliveryTime: "15-25 min",
    deliveryTimeMin: 20,
    deliveryFee: 1.99,
    priceLevel: 1,
    isOpen: true,
    minOrder: 8,
    dietaryOptions: ["Non-Vegetarian"],
  },
  {
    id: 3,
    name: "Xamar Traditional Kitchen",
    cuisine: "Somali, East African",
    description: "Home-style Somali dishes made with fragrant spices, tender meats, and basmati rice.",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=200&q=80",
    rating: 4.9,
    reviewCount: 1560,
    deliveryTime: "25-35 min",
    deliveryTimeMin: 30,
    deliveryFee: 2.0,
    priceLevel: 2,
    isOpen: true,
    minOrder: 12,
    dietaryOptions: ["Halal"],
  },
  {
    id: 4,
    name: "Golden Fried Chicken",
    cuisine: "Fried Chicken, Fast Food",
    description: "Crispy golden fried chicken seasoned with our signature spice blend.",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=200&q=80",
    rating: 4.5,
    reviewCount: 870,
    deliveryTime: "20-30 min",
    deliveryTimeMin: 25,
    deliveryFee: 1.5,
    priceLevel: 1,
    isOpen: false,
    minOrder: 7,
    dietaryOptions: ["Halal"],
  },
  {
    id: 5,
    name: "Sweet Treats Bakery",
    cuisine: "Desserts, Bakery",
    description: "Freshly baked cakes, pastries, and desserts made daily with premium ingredients.",
    image: "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1517433367423-c7e5b0f35086?auto=format&fit=crop&w=200&q=80",
    rating: 4.7,
    reviewCount: 640,
    deliveryTime: "15-20 min",
    deliveryTimeMin: 18,
    deliveryFee: 2.25,
    priceLevel: 2,
    isOpen: true,
    minOrder: 6,
    dietaryOptions: ["Vegetarian"],
  },
  {
    id: 6,
    name: "Fresh Juice Bar",
    cuisine: "Drinks, Smoothies",
    description: "Cold-pressed juices and fruit smoothies made fresh to order, no added sugar.",
    image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=200&q=80",
    rating: 4.4,
    reviewCount: 410,
    deliveryTime: "10-20 min",
    deliveryTimeMin: 15,
    deliveryFee: 1.75,
    priceLevel: 1,
    isOpen: true,
    minOrder: 5,
    dietaryOptions: ["Vegan"],
  },
  {
    id: 7,
    name: "Spice Route Grill",
    cuisine: "Chicken, Grill",
    description: "Char-grilled chicken and skewers marinated in bold, smoky spice rubs.",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=200&q=80",
    rating: 4.6,
    reviewCount: 715,
    deliveryTime: "25-35 min",
    deliveryTimeMin: 30,
    deliveryFee: 2.75,
    priceLevel: 2,
    isOpen: true,
    minOrder: 10,
    dietaryOptions: ["Halal", "Gluten-Free"],
  },
  {
    id: 8,
    name: "Pasta Palace",
    cuisine: "Italian, Pasta",
    description: "Rich, creamy pasta dishes crafted from scratch with imported Italian ingredients.",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80",
    logo: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=200&q=80",
    rating: 4.3,
    reviewCount: 320,
    deliveryTime: "30-40 min",
    deliveryTimeMin: 35,
    deliveryFee: 3.0,
    priceLevel: 3,
    isOpen: false,
    minOrder: 15,
    dietaryOptions: ["Vegetarian"],
  },
];

// ---------- Popular Dishes / Food Items ----------
// Every restaurant has at least 4 food items with correct restaurantId links.
const foodItems = [
  // Bella Italia (restaurantId: 1)
  {
    id: 1,
    name: "Margherita Pizza",
    description: "Classic pizza topped with fresh mozzarella, tomato sauce, and basil.",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80",
    category: "Pizza",
    restaurantId: 1,
    rating: 4.8,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 7,
    name: "Pepperoni Pizza",
    description: "Loaded with spicy pepperoni and extra mozzarella cheese.",
    price: 10.99,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80",
    category: "Pizza",
    restaurantId: 1,
    rating: 4.7,
    dietaryType: "Non-Vegetarian",
    available: true,
  },
  {
    id: 11,
    name: "Quattro Formaggi Pizza",
    description: "A rich blend of four cheeses on a crispy thin crust.",
    price: 11.49,
    image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=600&q=80",
    category: "Pizza",
    restaurantId: 1,
    rating: 4.6,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 12,
    name: "Garlic Breadsticks",
    description: "Warm, buttery breadsticks brushed with garlic and herbs.",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80",
    category: "Pizza",
    restaurantId: 1,
    rating: 4.5,
    dietaryType: "Vegetarian",
    available: false,
  },

  // Burger Junction (restaurantId: 2)
  {
    id: 2,
    name: "Classic Cheeseburger",
    description: "Juicy beef patty with melted cheddar, lettuce, tomato, and house sauce.",
    price: 7.49,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    category: "Burgers",
    restaurantId: 2,
    rating: 4.6,
    dietaryType: "Non-Vegetarian",
    available: true,
  },
  {
    id: 9,
    name: "Double Bacon Burger",
    description: "Two beef patties stacked with crispy bacon, cheese, and BBQ sauce.",
    price: 9.49,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=600&q=80",
    category: "Burgers",
    restaurantId: 2,
    rating: 4.6,
    dietaryType: "Non-Vegetarian",
    available: true,
  },
  {
    id: 13,
    name: "Veggie Burger",
    description: "A hearty plant-based patty with avocado, lettuce, and vegan mayo.",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80",
    category: "Burgers",
    restaurantId: 2,
    rating: 4.4,
    dietaryType: "Vegan",
    available: true,
  },
  {
    id: 14,
    name: "Crispy Onion Rings",
    description: "Golden battered onion rings served with dipping sauce.",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=600&q=80",
    category: "Burgers",
    restaurantId: 2,
    rating: 4.5,
    dietaryType: "Vegetarian",
    available: true,
  },

  // Xamar Traditional Kitchen (restaurantId: 3)
  {
    id: 3,
    name: "Suqaar with Rice",
    description: "Tender diced beef sautéed with peppers and onions, served with fragrant rice.",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80",
    category: "Somali Food",
    restaurantId: 3,
    rating: 4.9,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 8,
    name: "Somali Sambusa (6 pcs)",
    description: "Crispy pastry pockets filled with spiced beef or vegetables.",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    category: "Somali Food",
    restaurantId: 3,
    rating: 4.8,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 15,
    name: "Bariis Iskukaris",
    description: "Spiced Somali rice cooked with raisins, carrots, and tender goat meat.",
    price: 9.49,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    category: "Somali Food",
    restaurantId: 3,
    rating: 4.9,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 16,
    name: "Malawah with Honey",
    description: "Soft, layered Somali pancake served with honey and cream.",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80",
    category: "Somali Food",
    restaurantId: 3,
    rating: 4.7,
    dietaryType: "Vegetarian",
    available: true,
  },

  // Golden Fried Chicken (restaurantId: 4)
  {
    id: 4,
    name: "Crispy Fried Chicken",
    description: "Golden crispy fried chicken pieces seasoned with signature spices.",
    price: 8.49,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 4,
    rating: 4.5,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 10,
    name: "Grilled Chicken Wings",
    description: "Smoky grilled wings tossed in a tangy house glaze.",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 4,
    rating: 4.5,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 17,
    name: "Chicken Tenders Basket",
    description: "Hand-breaded chicken tenders served with fries and dipping sauce.",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 4,
    rating: 4.4,
    dietaryType: "Halal",
    available: false,
  },
  {
    id: 18,
    name: "Spicy Chicken Burger",
    description: "Crispy spicy chicken fillet with pickles and chipotle mayo.",
    price: 6.49,
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 4,
    rating: 4.6,
    dietaryType: "Halal",
    available: true,
  },

  // Sweet Treats Bakery (restaurantId: 5)
  {
    id: 5,
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a gooey molten center, served with ice cream.",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=600&q=80",
    category: "Desserts",
    restaurantId: 5,
    rating: 4.7,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 19,
    name: "New York Cheesecake",
    description: "Rich and creamy cheesecake with a buttery graham cracker crust.",
    price: 5.49,
    image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=600&q=80",
    category: "Desserts",
    restaurantId: 5,
    rating: 4.8,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 20,
    name: "Assorted Macarons (6 pcs)",
    description: "Delicate French macarons in a variety of fruity flavors.",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=600&q=80",
    category: "Desserts",
    restaurantId: 5,
    rating: 4.6,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 21,
    name: "Vegan Carrot Cake",
    description: "Moist carrot cake with a dairy-free cream cheese frosting.",
    price: 5.99,
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80",
    category: "Desserts",
    restaurantId: 5,
    rating: 4.5,
    dietaryType: "Vegan",
    available: true,
  },

  // Fresh Juice Bar (restaurantId: 6)
  {
    id: 6,
    name: "Fresh Mango Smoothie",
    description: "Creamy blended mango smoothie made with real fruit and yogurt.",
    price: 4.49,
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    category: "Drinks",
    restaurantId: 6,
    rating: 4.4,
    dietaryType: "Vegan",
    available: true,
  },
  {
    id: 22,
    name: "Green Detox Juice",
    description: "Cold-pressed blend of kale, cucumber, apple, and lemon.",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=600&q=80",
    category: "Drinks",
    restaurantId: 6,
    rating: 4.3,
    dietaryType: "Vegan",
    available: true,
  },
  {
    id: 23,
    name: "Strawberry Banana Smoothie",
    description: "A refreshing blend of ripe strawberries, banana, and almond milk.",
    price: 4.79,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80",
    category: "Drinks",
    restaurantId: 6,
    rating: 4.5,
    dietaryType: "Vegan",
    available: true,
  },
  {
    id: 24,
    name: "Iced Lemon Mint Tea",
    description: "Chilled herbal tea infused with fresh lemon and mint leaves.",
    price: 3.49,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
    category: "Drinks",
    restaurantId: 6,
    rating: 4.2,
    dietaryType: "Vegan",
    available: true,
  },

  // Spice Route Grill (restaurantId: 7)
  {
    id: 25,
    name: "Peri Peri Grilled Chicken",
    description: "Half chicken marinated in fiery peri peri sauce and flame-grilled.",
    price: 10.49,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 7,
    rating: 4.7,
    dietaryType: "Gluten-Free",
    available: true,
  },
  {
    id: 26,
    name: "Chicken Kebab Skewers",
    description: "Tender chicken chunks marinated in spices, grilled on skewers.",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 7,
    rating: 4.6,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 27,
    name: "Grilled Chicken Platter",
    description: "A full platter of grilled chicken with rice, salad, and garlic sauce.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 7,
    rating: 4.8,
    dietaryType: "Halal",
    available: true,
  },
  {
    id: 28,
    name: "Spicy Chicken Soup",
    description: "A warming, spiced chicken broth soup with fresh herbs.",
    price: 5.49,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    category: "Chicken",
    restaurantId: 7,
    rating: 4.3,
    dietaryType: "Gluten-Free",
    available: false,
  },

  // Pasta Palace (restaurantId: 8)
  {
    id: 29,
    name: "Fettuccine Alfredo",
    description: "Creamy parmesan alfredo sauce tossed with fresh fettuccine pasta.",
    price: 10.99,
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80",
    category: "Pasta",
    restaurantId: 8,
    rating: 4.5,
    dietaryType: "Vegetarian",
    available: true,
  },
  {
    id: 30,
    name: "Spaghetti Bolognese",
    description: "Classic spaghetti tossed in a rich, slow-cooked meat sauce.",
    price: 11.49,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=600&q=80",
    category: "Pasta",
    restaurantId: 8,
    rating: 4.4,
    dietaryType: "Non-Vegetarian",
    available: true,
  },
  {
    id: 31,
    name: "Penne Arrabbiata",
    description: "Spicy tomato-based sauce with garlic and chili tossed in penne pasta.",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?auto=format&fit=crop&w=600&q=80",
    category: "Pasta",
    restaurantId: 8,
    rating: 4.2,
    dietaryType: "Vegan",
    available: true,
  },
  {
    id: 32,
    name: "Lasagna al Forno",
    description: "Layers of pasta, rich meat sauce, and melted cheese baked to perfection.",
    price: 12.49,
    image: "https://images.unsplash.com/photo-1619895092538-128341789043?auto=format&fit=crop&w=600&q=80",
    category: "Pasta",
    restaurantId: 8,
    rating: 4.6,
    dietaryType: "Non-Vegetarian",
    available: true,
  },
];

// ---------- Special Offers ----------
const specialOffers = [
  {
    id: 1,
    title: "50% Off Your First Order",
    description: "New to FreshBite? Enjoy half off your first order from any restaurant.",
    code: "WELCOME50",
    discount: "50%",
    expiry: "2026-08-31",
    icon: "fa-solid fa-gift",
  },
  {
    id: 2,
    title: "Free Delivery on Orders Over $20",
    description: "Skip the delivery fee when you order $20 or more from participating restaurants.",
    code: "FREEDEL20",
    discount: "Free Delivery",
    expiry: "2026-08-15",
    icon: "fa-solid fa-truck",
  },
  {
    id: 3,
    title: "Buy One Get One Free - Pizza",
    description: "Order any large pizza and get a second one absolutely free.",
    code: "PIZZABOGO",
    discount: "BOGO",
    expiry: "2026-08-05",
    icon: "fa-solid fa-pizza-slice",
  },
  {
    id: 4,
    title: "20% Off Weekend Orders",
    description: "Treat yourself every weekend with 20% off all orders over $15.",
    code: "WEEKEND20",
    discount: "20%",
    expiry: "2026-09-30",
    icon: "fa-solid fa-calendar-week",
  },
];

// ---------- Cart Coupons ----------
// type: "percent" | "flat" | "freeDelivery"
// discountType: "percent" | "flat" | "freeDelivery"
// condition: "none" | "pizzaOnly" | "firstOrderOnly"
const coupons = [
  {
    code: "FRESH10",
    description: "10% off your order",
    discountType: "percent",
    discountValue: 10,
    minOrder: 10,
    expiry: "2026-12-31",
    condition: "none",
    active: true,
  },
  {
    code: "WELCOME5",
    description: "$5 off your order",
    discountType: "flat",
    discountValue: 5,
    minOrder: 15,
    expiry: "2026-12-31",
    condition: "none",
    active: true,
  },
  {
    code: "FREEDELIVERY",
    description: "Free delivery on this order",
    discountType: "freeDelivery",
    discountValue: 0,
    minOrder: 0,
    expiry: "2026-12-31",
    condition: "none",
    active: true,
  },
  {
    code: "PIZZA20",
    description: "20% off eligible pizza items",
    discountType: "percent",
    discountValue: 20,
    minOrder: 0,
    expiry: "2026-12-31",
    condition: "pizzaOnly",
    active: true,
  },
  {
    code: "FIRSTORDER",
    description: "15% off your very first FreshBite order",
    discountType: "percent",
    discountValue: 15,
    minOrder: 0,
    expiry: "2026-12-31",
    condition: "firstOrderOnly",
    active: true,
  },
];
